---
Atividade
1. Crie duas variáveis Ana e Paulo e atribua a elas valores de suas idades, sendo respectivamente 8 e 12 anos. As variáveis devem ser do tipo inteiro. Imprima no console "A menina é mais velha" ou "O menino é mais velho" como resultado de um teste lógico

2. BOD é um objeto existente do R. Verifique qual a classe deste objeto.

3. Crie um vetor que armazene números de 1 a 10 e posteriormente imprima os valores pares

4. women é um datarframe existente no R, Imprima as 10 últimas linhas

5. Use a função plot do R para produzir um gráfico do atributos Sepal.Width e Petal.Length do conjunto de dados Iris. O grafico deve imprimir apenas das linhas 50 até 100

6. Crie dois vetores de tamanhos iguais, some as posições equivalentes dos vetores e imprima o resultado.

7. Imprima o número de linhas, de colunas, nomes das linhas e nome das colunas do conjunto de dados CO2.


---
Questão 1
```{r}
Ana = 8L
Paulo = 12L

if (Ana > Paulo){
  print("A menina é mais velha")
}else{
  "O menino é mais velho"
}

```

Questão 2
```{r}
BOD
class(BOD)
```
Questão 3
```{r}
numeros = c(1,2,3,4,5,6,7,8,9,10)
for(i in numeros)
{
  if(i%%2==0){
    print(i)
  }
}

```
Questão 4
```{r}
women
tail(women, n=10)
```
Questão 5
```{r}
plot(iris[50:100,c(2,3)])

```
Questão 6
```{r}
primeiro_vetor = c(1L,2L,3L,4L,5L,6L)
segundo_vetor = c(4L,5L,6L,7L,8L,9L)
soma = primeiro_vetor + segundo_vetor
soma  
```
Questão 7
```{r}
CO2
dim(CO2)
colnames(CO2)
rownames(CO2)
```

